# Generated by Django 5.0.1 on 2024-04-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='code_snippets/'),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
